"""change in field

Revision ID: 9c9b2d6ecb32
Revises: 6d5b4b0bfd98
Create Date: 2025-04-09 13:48:42.327317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9b2d6ecb32'
down_revision = '6d5b4b0bfd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_constraint('users_email_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('email_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_email_id_key', ['email_id'])
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
